spring:
  application:
    name: SpringRepositoryDemo


  datasource:
    url: jdbc:mysql://localhost:3306/productDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xpy
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect